build_image:
    image: maven:3.5.0-jdk-8
    script:
        - mvn -f src/pom.xml verify --batch-mode -P test-consumer,test-business

test_docker:
    image: maven:3.5.0-jdk-8
    image: docker
    services:
        - docker:dind
    script:
        - apk add --no-cache py-pip
        - pip install docker-compose
        - docker volume create --name maven-repo
        - docker run -it -v maven-repo:/root/.m2 maven mvn archetype:generate # will download artifacts
        - docker-compose -f docker/dev/docker-compose.yml rm -v
        - docker-compose -f docker/dev/docker-compose.yml up -d
        - mvnw install -f src/pom.xml -P test-consumer,test-business
        - docker-compose -f docker/dev/docker-compose.yml stop
        - docker-compose -f docker/dev/docker-compose.yml rm -f
        - docker-compose -f docker/dev/docker-compose.yml up -d
        - docker-compose -f docker/dev/docker-compose.yml ps
