image: maven:3.5.0-jdk-8

buildAndTest:
  script:
    - mvn -f src/pom.xml verify --batch-mode -P test-consumer,test-business
    
image: docker

services:
  - docker:dind

build:
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - cd docker/dev
    - docker-compose up --timeout 60
    - docker-compose stop
