build:
    image: maven:3.5.0-jdk-8
    script:
        - mvn -f src/pom.xml verify --batch-mode -P test-consumer,test-business

test:
    image: docker
    services:
        - docker:dind
    script:
        - apk add --no-cache py-pip
        - pip install docker-compose
        - cd docker/dev
        - docker-compose up -d
